### ISSUE TITLE
"meteor.is_module_active" doesn't update

### ISSUE THREAD

**Issue by GameGuyOnYT** [MeteorDevelopment/starscript#10]
I am trying to make an element that checks if a module is on or off. I found `meteor.is_module_active` while checking the [Starscript FAQ](https://meteorclient.com/faq/starscript) on the website and used it on the following if statement:

`{meteor.is_module_active("autoTool") ? "Auto Tool is ON" : "Auto Tool is OFF"}`

When I use the code above, it doesn't update at all. Even when the module is on, it stays false. I would appreciate any help. Thanks!

**Comment by OskHe** [comment]
You have to use the actual module names like: `auto-tool`, `kill-aura` or `xray`.
If you use wrong names it will always be `false`.
`{meteor.is_module_active("auto-tool") ? "Auto Tool is ON" : "Auto Tool is OFF"}` would work.

**Comment by OskHe** [comment]
If you don't know the correct name, you can use the `.toggle` command to find it. The command shows the correct name in the command suggestions.

**Comment by GameGuyOnYT** [comment]
> You have to use the actual module names like: `auto-tool`, `kill-aura` or `xray`. If you use wrong names it will always be `false`. `{meteor.is_module_active("auto-tool") ? "Auto Tool is ON" : "Auto Tool is OFF"}` would work.

This worked, thank you so much!
