### ISSUE TITLE
[ENCHANCEMENT] Get/Use the name of the command executor

### ISSUE THREAD

**Issue by Devcom439** [MeteorDevelopment/starscript#23]
Hey this is not an issue, but it would be very useful if this feature would exist.

It would be soo useful if you can get the name of the person executing the chat bot command. For example: If I, Joe, would type `!hello` it would say "Name: Joe" since I put in `Name: {player}` . But if someone else would execute the command it still says "Name: Joe" and not the name of that player. This absolutely makes sense, but it would make for a great addition. In this screenshot I used the prefix `"joe."`:
![image](https://github.com/user-attachments/assets/15754b22-6b31-42b7-9934-1b304b31a6bd)
![image](https://github.com/user-attachments/assets/f792887b-5293-4061-acb9-581893be7eec)

As you can see, even if someone else executes the command it still outputs my name.

**Comment by RacoonDog** [comment]
This is the starscript repository, it has nothing to do with minecraft
