### ISSUE TITLE
{player.health} won't count absorption

### ISSUE THREAD

**Issue by Fadnix** [MeteorDevelopment/starscript#8]
{player.health} will not count absorption health, so if you eat an egap it will show 20 but in reality its 36
![image](https://user-images.githubusercontent.com/109868859/228655117-1076d3a4-de1d-4978-aaee-f24b7950c10e.png)
![image](https://user-images.githubusercontent.com/109868859/228655225-452f4b60-e30b-4209-9f97-de990d106fef.png)

**Comment by RacoonDog** [comment]
meteor issue, not starscript

**Comment by Talhoid** [comment]
lets see who can spot it and make the pr faster

**Comment by Talhoid** [comment]
there doesnt seem to be a cap on the starscript output value, must be from the utils

**Comment by arlomcwalter** [comment]
MeteorDevelopment/meteor-client#3533

this, and the issue, are wrong imo. absorption is handled differently than health within the game and i don't see why it shouldn't be so in starscript. imo the change should be just to add absorption as a variable on its own, users can do player.health + player.absorption if they want to, it just makes more sense logically to me

**Comment by arlomcwalter** [comment]
closing this anyway since its in the wrong repo
